#!/usr/bin/env bash
set -euo pipefail

# Co-Founder Action System — Router
# ADR: ~/.openclaw/adrs/ADR-0005-action-system.md
#
# Routes actions from a parsed JSON file:
# 1. Creates GitHub Issues (source of truth) for each action
# 2. Posts Discord notifications linking to the issues
# 3. Architecture lens actions with a target repo auto-spawn into PRs
#    All other actions require Patrick's approval via /cofounder approve.
#
# Usage: action-router.sh <actions-json-file> [briefing-thread-id]
# Called from co-founder.sh after extracting actions from briefing output.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/config.sh"
# Queue helpers — inline enqueue (daemon picks up in ≤30s)
QUEUE_FILE="$HOME/.openclaw/monitor/task-queue.json"
QUEUE_PROMPTS_DIR="$HOME/.openclaw/monitor/queue-prompts"

_ensure_queue_infra() {
    mkdir -p "$QUEUE_PROMPTS_DIR"
    [[ -f "$QUEUE_FILE" ]] || echo '{"queue":[]}' > "$QUEUE_FILE"
}

enqueue_task() {
    local task_id="$1" repo="$2" description="$3" prompt="$4" actions_file="${5:-}" action_index="${6:-0}" issue_number="${7:-}" briefing_thread="${8:-}"
    _ensure_queue_infra
    echo "$prompt" > "$QUEUE_PROMPTS_DIR/${task_id}.txt"
    local entry
    entry="$(jq -n \
        --arg tid "$task_id" --arg repo "$repo" --arg desc "$description" \
        --arg pf "$QUEUE_PROMPTS_DIR/${task_id}.txt" \
        --arg af "$actions_file" --argjson ai "$action_index" \
        --arg issue "$issue_number" \
        --arg bt "$briefing_thread" \
        --arg ts "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
        '{task_id: $tid, repo: $repo, description: $desc, prompt_file: $pf, actions_file: $af, action_index: $ai, issue_number: $issue, briefing_thread_id: $bt, queued_at: $ts}')"
    local tmp="${QUEUE_FILE}.tmp.$$"
    jq --argjson entry "$entry" '.queue += [$entry]' "$QUEUE_FILE" > "$tmp" && mv "$tmp" "$QUEUE_FILE"
    jq '.queue | length' "$QUEUE_FILE"
}

ACTIONS_FILE="${1:?Usage: action-router.sh <actions-json-file> [briefing-thread-id]}"
BRIEFING_THREAD_ID="${2:-}"

if [[ ! -f "$ACTIONS_FILE" ]]; then
    echo "ERROR: Actions file not found: $ACTIONS_FILE" >&2
    exit 1
fi

# Validate JSON
if ! jq empty "$ACTIONS_FILE" 2>/dev/null; then
    echo "ERROR: Invalid JSON in $ACTIONS_FILE" >&2
    exit 1
fi

ACTION_COUNT="$(jq '.actions | length' "$ACTIONS_FILE")"
echo "[$(date '+%Y-%m-%d %H:%M')] Routing $ACTION_COUNT actions from $ACTIONS_FILE"

GITHUB_REPO="patrickkidd/theapp"

discord_post_to_channel() {
    local channel_id="$1"
    local message="$2"

    # Hard truncate for Discord
    if [[ ${#message} -gt 2000 ]]; then
        message="${message:0:1997}..."
    fi

    local response
    response="$(curl -s -X POST "https://discord.com/api/v10/channels/${channel_id}/messages" \
        -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
        -H "Content-Type: application/json" \
        -d "$(jq -n --arg content "$message" '{content: $content}')")" || {
        echo "WARNING: Discord post failed for channel $channel_id" >&2
        return 1
    }

    # Return message ID for linking
    echo "$response" | jq -r '.id // empty'
    sleep 1
}

for i in $(seq 0 $((ACTION_COUNT - 1))); do
    ACTION="$(jq ".actions[$i]" "$ACTIONS_FILE")"
    ID="$(echo "$ACTION" | jq -r '.id')"
    TITLE="$(echo "$ACTION" | jq -r '.title')"
    CATEGORY="$(echo "$ACTION" | jq -r '.category')"
    EFFORT="$(echo "$ACTION" | jq -r '.effort')"
    CONFIDENCE="$(echo "$ACTION" | jq -r '.confidence')"
    REPO="$(echo "$ACTION" | jq -r '.repo // "none"')"
    PLAN="$(echo "$ACTION" | jq -r '.plan // ""')"
    SPAWN_PROMPT="$(echo "$ACTION" | jq -r '.spawn_prompt // ""')"
    SUCCESS_METRIC="$(echo "$ACTION" | jq -r '.success_metric // ""')"

    echo "[$(date '+%Y-%m-%d %H:%M')] Processing action: $ID ($CATEGORY, $EFFORT)"

    # --- 1. Create GitHub Issue ---
    LABELS="co-founder,propose,$CATEGORY"

    # Extract lens name from action ID — handles both date format (architecture-2026-02-27-1)
    # and non-date format (architecture-latest-1). Take first segment before a date or a number.
    LENS_NAME="$(echo "$ID" | sed -E 's/-(20[0-9]{2}-[0-9]{2}-[0-9]{2}|latest|[0-9]+).*//')"

    ISSUE_BODY="$(cat <<EOF
## Co-Founder Action: $TITLE

**ID:** \`$ID\`
**Category:** $CATEGORY | **Effort:** $EFFORT | **Confidence:** $CONFIDENCE
**Repo:** $REPO | **Lens:** $LENS_NAME

---

### Plan

$PLAN

### Spawn Prompt

\`\`\`
$SPAWN_PROMPT
\`\`\`

### Success Metric

$SUCCESS_METRIC

---

*Generated by co-founder system — [ADR-0005](https://github.com/$GITHUB_REPO/wiki/ADR-0005)*
Approve: \`/cofounder approve $ID\` | Refine: \`/cofounder refine $ID <feedback>\`
EOF
)"

    ISSUE_URL=""
    ISSUE_NUMBER=""
    ISSUE_RESULT="$(gh issue create \
        --repo "$GITHUB_REPO" \
        --title "[co-founder] $TITLE" \
        --body "$ISSUE_BODY" \
        --label "$LABELS" \
        --assignee "patrickkidd" 2>&1)" && {
        ISSUE_URL="$ISSUE_RESULT"
        ISSUE_NUMBER="$(echo "$ISSUE_URL" | grep -o '[0-9]*$')"
        echo "  → GitHub Issue created: $ISSUE_URL"
    } || {
        echo "  WARNING: GitHub issue creation failed: $ISSUE_RESULT" >&2
        ISSUE_URL="(issue creation failed)"
    }

    # Update actions JSON with issue URL
    jq ".actions[$i].issue_url = \"$ISSUE_URL\"" "$ACTIONS_FILE" > "${ACTIONS_FILE}.tmp" && mv "${ACTIONS_FILE}.tmp" "$ACTIONS_FILE"

    # --- 2. Determine emoji ---
    if [[ "$CATEGORY" == "revenue" ]]; then
        EMOJI="💰"
    else
        EMOJI="📋"
    fi

    # --- 3+4. Auto-spawn or await approval, notify #co-founder ---
    # Any action with a target that produces a reviewable artifact auto-spawns:
    #   - Code repos (btcopilot, familydiagram) → PR
    #   - Website → WordPress draft
    # Only repo=none (infrastructure/manual) requires manual /cofounder approve.
    # #quick-wins only gets the FINAL artifact (from check-agents.py on PR detect).
    if [[ "$REPO" == "website" ]]; then
        # Website actions — create WordPress draft directly
        echo "  → Website action: creating WordPress draft"
        "$SCRIPT_DIR/wp-draft.sh" \
            --title "$TITLE" \
            --content "$SPAWN_PROMPT" \
            --type "post" \
            --action-id "$ID" 2>&1 || {
            echo "  WARNING: WordPress draft creation failed for $ID" >&2
            jq ".actions[$i].status = \"spawn_failed\"" "$ACTIONS_FILE" > "${ACTIONS_FILE}.tmp" && mv "${ACTIONS_FILE}.tmp" "$ACTIONS_FILE"
            continue
        }
        jq ".actions[$i].status = \"queued\" | .actions[$i].approved_at = \"$(date -u '+%Y-%m-%dT%H:%M:%SZ')\"" "$ACTIONS_FILE" > "${ACTIONS_FILE}.tmp" && mv "${ACTIONS_FILE}.tmp" "$ACTIONS_FILE"

        # Notify in the briefing thread
        if [[ -n "$BRIEFING_THREAD_ID" ]]; then
            discord_post_to_channel "$BRIEFING_THREAD_ID" "🌐 WordPress draft created: **${TITLE}**
   → <${ISSUE_URL}>" > /dev/null
        fi

        echo "  → WordPress draft created: $ID"

    elif [[ "$REPO" != "none" ]]; then
        # Code repo action — auto-spawn into queue, PR is the review gate
        TASK_ID="cf-${ID}"

        # Always enqueue — daemon picks up in ≤30s
        echo "  → Enqueuing action: $TASK_ID"
        QUEUE_POS="$(enqueue_task "$TASK_ID" "$REPO" "[co-founder] $TITLE" "$SPAWN_PROMPT" "$ACTIONS_FILE" "$i" "$ISSUE_NUMBER" "$BRIEFING_THREAD_ID")"
        jq ".actions[$i].status = \"queued\" | .actions[$i].approved_at = \"$(date -u '+%Y-%m-%dT%H:%M:%SZ')\"" "$ACTIONS_FILE" > "${ACTIONS_FILE}.tmp" && mv "${ACTIONS_FILE}.tmp" "$ACTIONS_FILE"

        # Comment on GitHub issue
        if [[ -n "$ISSUE_NUMBER" ]]; then
            gh issue comment "$ISSUE_NUMBER" --repo "$GITHUB_REPO" \
                --body "🤖 Enqueued as task \`$TASK_ID\` (position $QUEUE_POS). Daemon picks up in ≤30s." 2>/dev/null || true
        fi

        # Notify in the briefing thread
        if [[ -n "$BRIEFING_THREAD_ID" ]]; then
            discord_post_to_channel "$BRIEFING_THREAD_ID" "🚀 Enqueued: **${TITLE}** → task \`$TASK_ID\` (position $QUEUE_POS)
   → <${ISSUE_URL}>" > /dev/null
        fi

        echo "  → Enqueued: $TASK_ID (position $QUEUE_POS)"
    else
        # repo=none — infrastructure/manual action, requires Patrick's approval
        if [[ -n "$BRIEFING_THREAD_ID" ]]; then
            discord_post_to_channel "$BRIEFING_THREAD_ID" "${EMOJI} Proposed (manual): **${TITLE}** [${EFFORT}, ${CATEGORY}]
   → <${ISSUE_URL}>
   \`/cofounder approve ${ID}\`" > /dev/null
        fi

        jq ".actions[$i].status = \"pending_approval\"" "$ACTIONS_FILE" > "${ACTIONS_FILE}.tmp" && mv "${ACTIONS_FILE}.tmp" "$ACTIONS_FILE"
        echo "  → Awaiting approval: /cofounder approve $ID"
    fi
done

# --- 5. Commit and push actions file ---
(
    cd "$HOME/.openclaw"
    ACTIONS_REL="co-founder/actions/$(basename "$ACTIONS_FILE")"
    git add "$ACTIONS_REL" 2>/dev/null || true
    git commit -m "co-founder: actions from $(basename "$ACTIONS_FILE" .json)" --no-gpg-sign 2>/dev/null || true
    git -c "credential.helper=!gh auth git-credential" push 2>/dev/null || {
        echo "[$(date '+%Y-%m-%d %H:%M')] WARNING: git push failed for actions" >&2
    }
)

echo "[$(date '+%Y-%m-%d %H:%M')] Action routing complete: $ACTION_COUNT actions processed"
